import { fireEvent, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import App from "../App";
import fixture from "./fixtures/m43-product.json";
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); sessionStorage.clear(); });
it("shows hard mapping with incomplete inspection and a separate service failure", async () => {
  window.history.pushState({}, "", "/");
  const failed = fixture.inventory.leaves[2]!;
  const run = { ...fixture.abstention, state: "partial_failed", results: fixture.abstention.results.slice(0, 2), failures: [{ leaf_id: failed.id, stage: "model", cause: "ModelConstructionError", failure_category: "analysis_failure", retryable: false }] };
  vi.stubGlobal("fetch", vi.fn((input: string) => Promise.resolve(new Response(JSON.stringify(input.endsWith("/config/product") ? fixture.configuration : input.includes("/applications/parse") ? fixture.inventory : run)))));
  render(<App/>);
  fireEvent.change(screen.getByLabelText("Dossier ZIP"), { target: { files: [new File(["zip"], "synthetic.zip")] } });
  fireEvent.click(screen.getByRole("button", { name: "Continue to options" }));
  await screen.findByText("Offline demonstration");
  fireEvent.click(screen.getByLabelText(/I confirm/));
  fireEvent.click(screen.getByRole("button", { name: "Parse and analyze" }));
  await screen.findByRole("heading", { name: "Review actions" });
  fireEvent.click(screen.getByRole("button", { name: "Document placement" }));
  expect(screen.getByText(/This status does not mean stale content was found/)).toBeVisible();
  expect(screen.getByText(/Proposed document recommendation: Reuse with a new context/)).toBeVisible();
  expect(screen.getAllByText("Next step")[0]).toBeVisible();
  expect(screen.getByText(fixture.inventory.leaves[0]!.href)).toBeVisible();
  fireEvent.click(screen.getByRole("button", { name: "Analysis service" }));
  expect(screen.getByRole("heading", { name: failed.title })).toBeVisible();
  expect(screen.getByText("No regulatory decision issued.")).toBeVisible();
  expect(screen.queryByRole("button", { name: "Parse and analyze" })).not.toBeInTheDocument();
});
